### ISSUE TITLE
Send/Upload reports

### ISSUE THREAD

**Issue by samlin001** [Alwin-Lin/ctsVerifierSample#1]
It should be easy for a tester to send/upload reports without connecting to a host nor adb commands.
A few solution ideas:
- Upload to an URL, e.g. GCP storage buckets
    - Users can input the URL, or use adb commands to setup by script
- By Sharing: https://developer.android.com/training/sharing/send

**Comment by Alwin-Lin** [comment]
Added in feature to share report with gmail or google drive
